spring.application.name=demo

# database設定
# spring.datasource.url=jdbc:mysql://localhost:3306/taskmanage?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://mysql:3306/taskmanage?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# spring.datasource.password=password
spring.datasource.password=root

# flyway設定
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,filesystem:/opt/migration

logging.level.org.flywaydb=DEBUG

logging.pattern.level=%5p [%X{requestId}]
logging.pattern.console=%d{HH:mm:ss.SSS} [%X{requestId}] %-5level %logger - %msg%n